### ISSUE TITLE
ImportError: No module named 'cd'

### ISSUE THREAD

**Issue by liqi0126** [otaheri/chamfer_distance#1]
When I run `from chamfer_distance import ChamferDistance`，it gives:
![image](https://user-images.githubusercontent.com/48043983/109968789-1b01c300-7d2e-11eb-8b02-5f548d0b95f6.png)

Any idea?

**Comment by HAN-oQo** [comment]
i have a same issue. Did you get any solution?

**Comment by liqi0126** [comment]
No, I end up implementing it by myself.

**Comment by otaheri** [comment]
What is your PyTorch version? have you tried with version 1.1.0? I just tried it, and it works. I will take a deeper look into this.

**Comment by liqi0126** [comment]
I use PyTorch 1.7.0.

**Comment by trungpham2606** [comment]
@otaheri 
The pytorch link you give is pytorch cpu ?
Iam using the pytorch 1.6.0 + gpu. When I run import chamfer_distance it built again and failed.

**Comment by otaheri** [comment]
@trungpham2606 If you already have any version of PyTorch installed, you don't have to install the one that is referred to in readme again. So, just go with your installed PyTorch version and it should work.

**Comment by otaheri** [comment]
@liqi17thu I noticed that the Ninja package was missing from the requirements. Now it is added and it should work if you reinstall the package. Let me know if it is not working. Also, you need a PyTorch with Cuda support.

**Comment by liqi0126** [comment]
Not working.... test with torch 1.7.1
![image](https://user-images.githubusercontent.com/48043983/116229531-323abb00-a789-11eb-92e5-e9da1940bb7c.png)

**Comment by otaheri** [comment]
Can you try the Colab notebook that I prepared [Here](https://colab.research.google.com/drive/173-DuwxmczPwRcz2BNQ7n7D17K0DhBzw?usp=sharing). I tried with torch1.7.1 and it works for me.

**Comment by liqi0126** [comment]
The Colab notebook works for me too. I guess it is the driver's problem. I use Cuda 11.0. Which version are you using?

**Comment by otaheri** [comment]
I used it with pytorch1.6 and cu9.2 before and now I am using PyTorch 1.8 and Cuda 10.2 and it is ok with both.

**Comment by SeanChenxy** [comment]
@liqi17thu @otaheri  Hi, I meet the same problem. Have you solved it? I wonder whether this is related to gcc/g++ version？

**Comment by lileitech** [comment]
> The Colab notebook works for me too. I guess it is the driver's problem. I use Cuda 11.0. Which version are you using?

cuda 11.0 also did not work for me
